#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := leds
CXXFLAGS += -std=gnu++17
CFLAGS += -std=c17
include $(IDF_PATH)/make/project.mk

